# Generated by Django 3.0.2 on 2021-05-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTransaction',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('tx_status', models.CharField(choices=[('CANCELLED', 'Cancelled'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('AWAITING_CONFIRMATIONS', 'Awaiting Confirmations'), ('PAYMENT_COMPLETE', 'Payment Complete')], default='AWAITING_PAYMENT', max_length=255)),
                ('currency', models.CharField(choices=[('BTC', 'Btc'), ('ETH', 'Eth'), ('XRP', 'Xrp'), ('XMR', 'Xmr'), ('BNB', 'Bnb'), ('LTC', 'Ltc'), ('USDC', 'Usdc')], max_length=255)),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=13)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=6)),
                ('receiving_address', models.TextField(max_length=64)),
                ('confirmations_needed', models.IntegerField(default=10, max_length=3)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('received_amount', models.IntegerField(default=0, max_length=3)),
                ('received_confirmations', models.IntegerField(default=0, max_length=3)),
                ('destination_tag', models.TextField(max_length=64, null=True)),
                ('qr_code_url', models.TextField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('gift_card', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='forum',
            name='last_thread',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='last_reply',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='threadprefix',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='threadprefix',
            name='incompatible_with',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='connections_discord',
        ),
        migrations.RemoveField(
            model_name='user',
            name='connections_telegram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='connections_twitter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='user',
            name='statistics_likes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='statistics_posts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.DeleteModel(
            name='ThreadPrefix',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
